### ISSUE TITLE
Node GYP error while having python 2 and 3 in my path -- This happens when doing npm install

### ISSUE THREAD

**Issue by Erik-Avakian** [ashutosh1919/masterPortfolio#171]
i have had this error the entire day. i have freshly installed node.js and python 2.7
i have added it to my path.
i am new to node.js so i don't really know what to look for when getting this sort of error, please help

```
npm ERR! code 1
npm ERR! path C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Python27" in the PATH
npm ERR! gyp verb `which` failed Error: not found: C:\Python27
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  C:\Python27 Error: not found: C:\Python27
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "C:\Python27". checking python launcher
npm ERR! gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
npm ERR! gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.1
npm ERR! gyp verb command install [ '16.13.1' ]
npm ERR! gyp verb install input version string "16.13.1"
npm ERR! gyp verb install installing version: 16.13.1
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.1
npm ERR! gyp verb build dir attempting to create "build" dir: C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\build\config.gypi
npm ERR! (node:18560) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2019',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\.node-gyp\\16.13.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\HeyZReD\\.node-gyp\\16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\HeyZReD\\.node-gyp\\16.13.1\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
npm ERR!     generator.CalculateVariables(default_variables, params)
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
npm ERR!     generator_flags.get('msvs_version', 'auto'))
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
npm ERR!     versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
npm ERR! KeyError: '2019'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\lib\configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HeyZReD\AppData\Local\npm-cache\_logs\2021-12-07T23_08_38_878Z-debug.log
```
![brave_JJQxlDZiMs](https://user-images.githubusercontent.com/90850836/144891381-47d7d513-0999-4227-a18d-02e9eb14797b.png)

**Comment by Erik-Avakian** [comment]
UPDATE: 

I still have this error but i seem to get a slightly different output now on the error messages. i am not 100% sure

```
npm ERR! code 1
npm ERR! path C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Python27" in the PATH
npm ERR! gyp verb `which` failed Error: not found: C:\Python27
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  C:\Python27 Error: not found: C:\Python27
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "C:\Python27". checking python launcher
npm ERR! gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
npm ERR! gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.18
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.1
npm ERR! gyp verb command install [ '16.13.1' ]
npm ERR! gyp verb install input version string "16.13.1"
npm ERR! gyp verb install installing version: 16.13.1
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.1
npm ERR! gyp verb build dir attempting to create "build" dir: C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\build\config.gypi
npm ERR! (node:18560) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass\common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2019',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\.node-gyp\\16.13.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\HeyZReD\\.node-gyp\\16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\HeyZReD\\.node-gyp\\16.13.1\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
npm ERR!     generator.CalculateVariables(default_variables, params)
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
npm ERR!     generator_flags.get('msvs_version', 'auto'))
npm ERR!   File "C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
npm ERR!     versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
npm ERR! KeyError: '2019'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-gyp\lib\configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HeyZReD\\Coding_Projects\\masterPortfolio\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\HeyZReD\Coding_Projects\masterPortfolio\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HeyZReD\AppData\Local\npm-cache\_logs\2021-12-07T23_08_38_878Z-debug.log
```

**Comment by Mayheptad** [comment]
@Erik-Avakian I had the same issue. after many hours of searching the internet,  StackOverflow, github topics, etc, no solutions. so decided to pay a closer look at the error and study the package.json very well.

SO it turns out that nodeJs v16 does not support node-sass v 4x, so the solution that worked for me is upgrading node-sass to at least v6.0 that was supported by the nodeJs v16 which I have installed on my PC. 

Since you also have nodeJs v16 instaled, Immediately u clone the Repo, open the package.json, and change node-sass to v6.0 like this "node-sass": "^6.0.0". 

If you want to stick to node-sass v4, then another alternative is to downgrade nodeJs to v14. 
Enjoy

**Comment by Erik-Avakian** [comment]
> @Erik-Avakian I had the same issue. after many hours of searching the internet, StackOverflow, github topics, etc, no solutions. so decided to pay a closer look at the error and study the package.json very well.
> 
> SO it turns out that nodeJs v16 does not support node-sass v 4x, so the solution that worked for me is upgrading node-sass to at least v6.0 that was supported by the nodeJs v16 which I have installed on my PC.
> 
> Since you also have nodeJs v16 instaled, Immediately u clone the Repo, open the package.json, and change node-sass to v6.0 like this "node-sass": "^6.0.0".
> 
> If you want to stick to node-sass v4, then another alternative is to downgrade nodeJs to v14. Enjoy

Hi, Thank you so much for the help. that fixed my issue. 
i am completely new to web stuff. i have only learned python so far so these npm errors didnt really make alot of sense to me at first.

now i get this Status message in the terminal after the "npm install" is finished.. is it something i should be worried about or can i just carry on customizing the template? Thanks again for the help!

**Comment by ashutosh1919** [comment]
@Erik-Avakian , you don't have to worry about warnings. Closing this issue. @Mayheptad , Thanks for comment.

**Comment by ahsansiddz1** [comment]
I have installed npm but its not starting 
Also node.js is installed and added to path.
I don't why I am getting error while opening npm
I have attached screenshot and errors that I am facing..
User Variables Path: 
 ![UserVariablePath](https://user-images.githubusercontent.com/79744131/146679106-eeafa956-4206-479a-93b1-e44c9dad5170.JPG)

System Variable Path:
![SystemVariablePath](https://user-images.githubusercontent.com/79744131/146679171-c932b2d9-924b-48ce-8a49-a21ecefe4fb9.JPG)

-----------------------------------------------------------------------------------------------------------------
Errors while installing npm: 
-----------------------------------------------------------------------------------------------------------------
````
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hpz\AppData\Local\npm-cache\_logs\2021-12-19T14_47_30_552Z-debug.log   

AHSAN@DESKTOP-EU5GIF6 MINGW64 ~/OneDrive/Desktop/masterPortfolio-master/masterPortfolio-master
$ npm help config
npm ERR! Invalid URL: file://C:%5CProgram%20Files%5Cnodejs%5Cnode_modules%5Cnpm%5Cdocs%5Coutput%5Ccommands%5Cnpm-config.html

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hpz\AppData\Local\npm-cache\_logs\2021-12-19T14_48_41_991Z-debug.log   

AHSAN@DESKTOP-EU5GIF6 MINGW64 ~/OneDrive/Desktop/masterPortfolio-master/masterPortfolio-master
````

-----------------------------------------------------------------------------------------------------------------
Errors while Starting npm: 
-----------------------------------------------------------------------------------------------------------------

`$ npm start

> masterPortfolio@0.1.0 start
> react-scripts start

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'react'
Require stack:
- C:\Users\hpz\AppData\Roaming\npm\node_modules\react-scripts\scripts\start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (C:\Users\hpz\AppData\Roaming\npm\node_modules\react-scripts\scripts\start.js:43:31)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)    
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\hpz\\AppData\\Roaming\\npm\\node_modules\\react-scripts\\scripts\\start.js'  
  ]
}

AHSAN@DESKTOP-EU5GIF6 MINGW64 ~/OneDrive/Desktop/masterPortfolio-master/masterPortfolio-master`

You help will be appreciated :)

**Comment by ahsansiddz1** [comment]
Finally  error resolved  with these commands:

react-scripts build

npm cache clean --force

npm i
