### ISSUE TITLE
I got error when execute git_data_fecher.mjs 

### ISSUE THREAD

**Issue by Rodrigo-Palma** [ashutosh1919/masterPortfolio#184]
$ node git_data_fetcher.mjs
/home/legion/rodrigo-palma/rodrigo-palma.github.io/git_data_fetcher.mjs:1
import fetch from 'node-fetch';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

How can I fix that?

**Comment by KasRoudra** [comment]
@Rodrigo-Palma Did you run a `npm install` before executing that? You need to run that first

**Comment by Rodrigo-Palma** [comment]
Yes, I do, maybe docker solve my case, I realize that npm install doesn't had install node-fetch and fs. I had try in ubuntu, windows, VMs with different versions of node and npm. Maybe package.json need update.

**Comment by MendezMadrigal** [comment]
Hello, were you able to solve this problem?

**Comment by saiteja13427** [comment]
This issue is mostly due to older nodejs on your system
