### ISSUE TITLE
I having following Issues after  { npm start } command

### ISSUE THREAD

**Issue by Bimalkhimdung** [ashutosh1919/masterPortfolio#289]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Website\masterPortfolio\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\Website\masterPortfolio\node_modules\babel-loader\lib\index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0

**Comment by Bimalkhimdung** [comment]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Website\masterPortfolio\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\Website\masterPortfolio\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\Website\masterPortfolio\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
D:\Website\masterPortfolio\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Website\masterPortfolio\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\Website\masterPortfolio\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\Website\masterPortfolio\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\Website\masterPortfolio\node_modules\babel-loader\lib\index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by ashutosh1919** [comment]
@Bimalkhimdung upgrade node to v16
